### ISSUE TITLE
Add option to retrieve old version of master by  using `version(-#)`

### ISSUE THREAD

**Issue by randrescastaneda** [GPID-WB/pcn#16]
Hi David, 

Could you please add an option to `pcn` in which we can retrieve any version of the master file by using the syntax `version(-#)` in which `#` refers to the number of versions before the current version?

For example, if I type `pcn master, load(Population) version(-1)` I will always load the version of the master file that was available right before the current version. If I use `version(-2)` instead, it will load the master file two versions before the current one, and so on and so forth. 

Please, let me know if you have any doubt. 

Thanks. 

PS: Ideally, this feature should be available for any vintage control file that we use.

**Comment by davidlvargas** [comment]
Hi Andres, 

This is working now for pcn master, load cpi and load price framework (pf). Still missing for pcn primus load, as the syntax is quite different, I'm working on that.

I just let you know in case you need to use the feature soon. 

Cheers, 
David.

**Comment by randrescastaneda** [comment]
Great. Thanks.

----------------------
R.Andrés Castañeda
